AFRPAY-11523: Magento improvements - update logos & text description
JumiaPayAIG/magento-plugin pull request #4
Opened 2022-07-19 13:22 UTC by mohabkandil

2022-09-14 11:37 UTC, ashrafhofney submitted a review, later dismissed

2022-09-14 15:33 UTC, amr-beshr approved these changes

2022-12-19 11:14 UTC, cacevedojumee submitted a review, later dismissed

2022-12-20 13:22 UTC, jmsakr approved these changes

2022-12-20 13:22 UTC, jmsakr approved these changes

2022-12-29 17:43 UTC, ashrafhofney requested changes

2022-12-29 17:43 UTC, ashrafhofney commented on view/frontend/web/js/view/payment/method-renderer/jpay-method.js
> +        switch (wpConfig.country) {
wpConfig is always empty after testing

2022-12-29 17:43 UTC, ashrafhofney commented on view/frontend/web/js/view/payment/method-renderer/jpay-method.js
> +        switch (wpConfig.country) {
which leads to always returning 'jpay-logo-no-country' class

2022-12-29 17:44 UTC, ashrafhofney commented on view/frontend/web/js/view/payment/method-renderer/jpay-method.js
> +        switch (wpConfig.country) {
@mohabkandil let me know when this is updated

2022-12-29 18:03 UTC, amr-beshr approved these changes

2022-12-29 18:04 UTC, merged